IDEA-Research/Grounded-Segment-Anything

- .gitignore
- README.md
- grounding_dino_demo.py
1. Debug the imported path in `grounding_dino_demo.py`.
2. Install diffusers in README.
> debug demo

- GroundingDINO/groundingdino/util/slconfig.py
- gradio_app.py
add “temp_config_file.close()” in slconfig.py and merge all models into the "checkpoints" folder
Now it can be successfully run in Windows 11 with Anaconda
> merge checkpoints and fix bugs

- README.md
edit the documents to fit the last PR
> edit the documents to fit the last PR

- GroundingDINO/groundingdino/util/slconfig.py
> Fix Windows Compatibility Issue

- automatic_label_demo.py
It's a small change that probably doesn't affect the end result, but hey, doesn't hurt to get the spelling checked, right? 
;)
> Fix typo in OpenAI prompt

- grounded_sam.ipynb
> fix notebook bugs

- gradio_app.py
I slightly refactored the gradio app.
- Optimized the loading of the model, only loading it on the first use instead of every time.
- Simplified and reused some function methods.
- Avoiding useless disk IO when displaying images.
- Use Gallery to display multiple output images.
- Added an optional startup arg `no-gradio-queue` to avoid errors when under proxy network.
> Optimize and refactor the gradio app

- README.md
Hi Grounded-Segment-Anything team,
Thanks for your great work. 
In [3D-Box-Segment-Anything](https://github.com/dvlab-research/3D-Box-Segment-Anything), we extend Segment Anything to 3D perception by combining it with [VoxelNeXt](https://github.com/dvlab-research/VoxelNeXt).
It would be much appreciated that if you can combine this into the README.
Regards,
Yukang Chen
> 3D-Box-Segment-Anything

- automatic_label_tag2text_demo.py
> Tag2Text + Grounded-SAM

- grounding_dino_demo.py
text_threshold = args.box_threshold should be  text_threshold = args.text_threshold
> fix a error

- Dockerfile
- Makefile
1. Add missing dependencies from docker file
2. Download models in the Makefile if they are not already there
> Download model checkpoints, add missing dependenceis

- README.md
- grounded_sam_inpainting_demo.py
- grounded_sam_simple_demo.py
- grounding_dino_demo.py
- This PR aims to build a cleaner README for users
Some README designs were borrowed from
- https://github.com/Hedlen/awesome-segment-anything
- https://github.com/Hedlen/awesome-segment-anything
- https://github.com/open-mmlab/mmyolo
> Refine README

- README.md
- playground/ImageBind_SAM/README.md
- playground/ImageBind_SAM/audio_referring_seg_demo.py
- playground/ImageBind_SAM/image_referring_seg_demo.py
- playground/ImageBind_SAM/text_referring_seg_demo.py
> Refine ImageBind-SAM playground

- README.md
- grounded_sam_demo.py
- segment_anything/segment_anything/__init__.py
- segment_anything/segment_anything/build_sam_hq.py
- segment_anything/segment_anything/modeling/__init__.py
- segment_anything/segment_anything/modeling/image_encoder.py
- segment_anything/segment_anything/modeling/mask_decoder_hq.py
- segment_anything/segment_anything/predictor.py
- Try sam-hq:
```bash
export CUDA_VISIBLE_DEVICES=0
python grounded_sam_demo.py \
--config GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py \
--grounded_checkpoint groundingdino_swint_ogc.pth \
--sam_hq_checkpoint sam_hq_vit_h.pth \
--use_sam_hq \
--input_image assets/inpaint_demo.jpg \
--output_dir "outputs" \
--box_threshold 0.3 \
--text_threshold 0.25 \
--text_prompt "bench." \
--device "cuda"
```
> Support SAM-HQ

- README.md
Hi team 👋🏻 
Last week Roboflow team published autodistill library that leverages models like GroundedSAM to train real-time object detection and image segmentation models with minimal amount of annotated data. I thought it would be cool `README.md` addition.
By the way, I wanted to ask if you plan to be at CVPR? Maybe there will be an opportunity to see each other in person.
> Add Grounded-SAM + `autodistill` tutorial to `README.md`

- GroundingDINO/pyproject.toml
see https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/358
> Fixes bug, that reports torch not importable although installed beforehand for GroundedDINO

- README.md
Release RAM++, which is the next generation of RAM. RAM++ can recognize any category with high accuracy, including both predefined common categories and diverse open-set categories.
> Release RAM++

- grounded_sam_demo.py
There are some unused imports and also we get module related error "No module named 'groundingdino/segment_anything'" . Related issue : [https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/43](https://github.com/IDEA-Research/Grounded-Segment-Anything/commit/related_issue)
> Updated grounded_sam_demo : removed unused imports and added modules to system path

- GroundingDINO/groundingdino/models/GroundingDINO/backbone/swin_transformer.py
- GroundingDINO/groundingdino/models/GroundingDINO/transformer.py
- GroundingDINO/groundingdino/models/GroundingDINO/utils.py
- grounding_dino_demo.py
this is 15% faster with almost no consequence
> support fp16 inference for grounding_dino

- EfficientSAM/grounded_efficient_sam.py
- EfficientSAM/grounded_light_hqsam.py
- EfficientSAM/grounded_repvit_sam.py
Hi team!
Thanks for this nice work. I found some parameter passing errors with a couple of files in EfficientSAM and fixed them.
> fix some parameter passing errors in EfficientSAM

- grounded_sam.ipynb
Fixed variable usage and added support for CPU devices.
* The `device` variable had not been declared ever
* CPU device needs to use **float32** to initialize the `StableDiffusionInpaintPipeline` 
- [grounded_sam.ipynb](https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/grounded_sam.ipynb)
- [grounded_sam.ipynb](https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/grounded_sam.ipynb)
> [Feature & Fix] Fixed variable usage and added support for CPU devices

- README.md
I created a robotic arm assistant that uses Grounded-SAM to perform detection and segmentation of objects in front of the robot arm, so that the arm knows which object to manipulate. Would love for my project to get featured in the list of extension projects. Thanks!
> add Tabletop HandyBot extension project
